---
title: "Hypothese5"
author: "Silas Nöttling"
date: "19 4 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r libs, include=FALSE}
library(ggplot2)
library(tidyverse)
library(dplyr)
library(stats)
library(xts)
library(forecast)
library(stats)
library(lmtest)
```

```{r setwd, include=FALSE}
setwd("C:/Users/maxku/OneDrive/Documents/Silas/Silas_Project")
```

```{r readxlsx}
# read-in excel data
df <- readxl::read_excel("Data_Is_Key.xlsx")
```

```{r datawrangling, include=FALSE}
# rename and convert Data
df <- df %>% rename(Datum = `Datum (jjmmtt)`) %>% mutate(Datum = as.Date(Datum, format = "%y%m%d"))

df <- df %>% mutate_at(c("Flughafen", "Airline", "Zeit", "Device", "Datenzugriff"), as.factor) %>% 
  mutate_at(c("Cookies", "IP-Adresse"), as.logical)

df <- df %>% rename(Preis = `Preis (€)`) %>% rename(IP_Adresse = `IP-Adresse`)

levels(df$Flughafen) <- c('Amsterdam', 'Berlin', 'Lissabon', 'London', 'Bangkok', 'New York', 'Tokio')
levels(df$Airline) <- c('AUA', 'KLM', 'EZY', 'LDM', 'BAW', 'THA', 'UAL', 'ANA')

```

````{r data_H5}
# H6 = H5

# filter data
df5 <- df %>%
  filter(Datenzugriff == 0 & IP_Adresse == FALSE & Device %in% c(0, 1)) %>% 
  unite(Flughafen_Airline, c("Flughafen", "Airline"), sep = "-") %>% 
  select(Preis, Cookies, Datum, Zeit, Flughafen_Airline) %>% 
  unite(DatumZeit, c("Datum", "Zeit"), sep = "")
#colnames(df5)[2]<-"Cookies_reset"


# filter data
df5.1 <- df %>%
  filter(Datenzugriff == 0 & IP_Adresse == FALSE & Device == 0 & Cookies == FALSE) %>% 
  select(Preis, Cookies, Datum, Zeit) %>% 
  unite(DatumZeit, c("Datum", "Zeit"), sep = "")

df5.2 <- df %>%
  filter(Datenzugriff == 0 & IP_Adresse == FALSE & Device == 1 & Cookies == TRUE) %>% 
  select(Preis, Cookies, Datum, Zeit)%>% 
  unite(DatumZeit, c("Datum", "Zeit"), sep = "")


#colnames(df5.1)[2]<-"Cookies_reset"
#colnames(df5.2)[2]<-"Cookies_reset"


#Join equal dates:

df5_1 <- df5.1
df5_3 <- df5.2
df5_date <- df5_1 %>% dplyr::inner_join(df5_3, by = 'DatumZeit') %>% select(DatumZeit) %>% unique()
df5 <- df5 %>% dplyr::filter(DatumZeit %in% df5_date$DatumZeit)

df5$Cookies <- factor(df5$Cookies)
levels(df5$Cookies) <- c('Zugelassen', 'Zurueckgesetzt')
````

## Deskriptive Statistik - Einzelflüge
````{r}
temp <- c()
for (flug in unique(df5$Flughafen_Airline)){
  
  #filter flug
  df5_single <- df5 %>% dplyr::filter(Flughafen_Airline == flug)
  
  # Deskreptive Statistik:
    temp <- c(temp, jmv::descriptives(df5, vars = c("Preis", "Cookies"), sd = TRUE, missing = TRUE, freq = TRUE))

  
}
names(temp) <- paste('Flug:', unique(df5$Flughafen_Airline))
temp
````

## Box-Plot - Einzelflüge
````{r, fig.width=15, fig.height=7}

for (flug in unique(df5$Flughafen_Airline)){
  df5_single <- df5 %>% dplyr::filter(Flughafen_Airline == flug)
  
  # Plot Box_Plot
  gp<-ggplot(df5, aes(Cookies, Preis)) +
  geom_boxplot(aes(fill = Cookies), show.legend = TRUE) +
  geom_point() +
  ggtitle(paste('Flug:', flug))
  
  print(gp)

}

````


## ANOVA
````{r, fig.width=15, fig.height=7}
temp <- c()
for (flug in unique(df5$Flughafen_Airline)){
  df5_single <- df5 %>% dplyr::filter(Flughafen_Airline == flug)
  
  # Mehrfakorielle ANOVA:
Anova5<-jmv::ANOVA(data = df5, 
                   dep = "Preis",
                   factors = c("Cookies"),
                   modelTerms = list("Cookies"),
                   effectSize = "partEta",
                   emMeans = list("Cookies"
                   ),
                   emmTables = TRUE,
                   emmPlots = FALSE)
Anova5
  temp <- c(temp, Anova5)
}
names(temp) <- paste('Flug:', unique(df5$Flughafen_Airline))
temp
````
