---
title: "Hypothese4"
author: "Silas Nöttling"
date: "19 4 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r libs, include=FALSE}
library(ggplot2)
library(tidyverse)
library(dplyr)
library(stats)
library(xts)
library(forecast)
library(stats)
library(lmtest)
```

```{r setwd, include=FALSE}
setwd("C:/Users/maxku/OneDrive/Documents/Silas/Silas_Project")
```

```{r readxlsx}
# read-in excel data
df <- readxl::read_excel("Data_Is_Key.xlsx")
```

```{r datawrangling, include=FALSE}
# rename and convert Data
df <- df %>% rename(Datum = `Datum (jjmmtt)`) %>% mutate(Datum = as.Date(Datum, format = "%y%m%d"))

df <- df %>% mutate_at(c("Flughafen", "Airline", "Zeit", "Device", "Datenzugriff"), as.factor) %>% 
  mutate_at(c("Cookies", "IP-Adresse"), as.logical)

df <- df %>% rename(Preis = `Preis (€)`) %>% rename(IP_Adresse = `IP-Adresse`)

levels(df$Flughafen) <- c('Amsterdam', 'Berlin', 'Lissabon', 'London', 'Bangkok', 'New York', 'Tokio')
levels(df$Airline) <- c('AUA', 'KLM', 'EZY', 'LDM', 'BAW', 'THA', 'UAL', 'ANA')

```


````{r}
#filter data frame: Website, Application
df4 <- df %>%
  filter(Datenzugriff %in% c(0,1) & Cookies == TRUE & IP_Adresse == FALSE) %>% 
  unite(Flughafen_Airline, c("Flughafen", "Airline"), sep = "-") %>% 
  select(Datum, Preis, Device, Flughafen_Airline) 


# Change factor levels:
df4$Device<-as.numeric(df4$Device)
df4$Device <- df4$Device - 1
df4 <- df4 %>% filter(Device %in% c(1,3))
df4$Device <- as.factor(df4$Device)

#Join equal dates:

df4_1 <- df4 %>% dplyr::filter(Device == 1)
df4_3 <- df4 %>% dplyr::filter(Device == 3)
df4_date <- df4_1 %>% dplyr::inner_join(df4_3, by = 'Datum') %>% select(Datum) %>% unique()
df4 <- df4 %>% dplyr::filter(Datum %in% df4_date$Datum)

levels(df4$Device) <- c('Apple Ipad', 'Mac Book')
````

## Deskriptive Statistik - Einzelflüge
````{r}
temp <- c()
for (flug in unique(df4$Flughafen_Airline)){
  
  #filter flug
  df4_single <- df4 %>% dplyr::filter(Flughafen_Airline == flug)
  
  # Deskreptive Statistik:
    temp <- c(temp, jmv::descriptives(df4, vars = c("Preis", "Device"), sd = TRUE, missing = TRUE, freq = TRUE))

  
}
names(temp) <- paste('Flug:', unique(df4$Flughafen_Airline))
temp
````

## Box-Plot - Einzelflüge
````{r, fig.width=15, fig.height=7}

for (flug in unique(df4$Flughafen_Airline)){
  df4_single <- df4 %>% dplyr::filter(Flughafen_Airline == flug)
  
  # Plot Box_Plot
  gp<-ggplot(df4, aes(Device, Preis)) +
  geom_boxplot(aes(fill = Device), show.legend = TRUE) +
  geom_point() +
    ggtitle(paste('Flug:', flug))
  
  print(gp)

}

````


## ANOVA
````{r, fig.width=15, fig.height=7}
temp <- c()
for (flug in unique(df4$Flughafen_Airline)){
  df4_single <- df4 %>% dplyr::filter(Flughafen_Airline == flug)
  
  # Mehrfakorielle ANOVA:
Anova4<-jmv::ANOVA(data = df4, 
                   dep = "Preis",
                   factors = c("Device"),
                   modelTerms = list("Device"),
                   effectSize = "partEta",
                   emMeans = list("Device"
                   ),
                   emmTables = TRUE,
                   emmPlots = FALSE)
Anova4
  temp <- c(temp, Anova4)
}
names(temp) <- paste('Flug:', unique(df4$Flughafen_Airline))
temp
````