---
title: "Hypothese 1"
author: "Silas Nöttling & Maximilian Kuttner"
date: "12 4 2020"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r libs, include=FALSE}
library(ggplot2)
library(tidyverse)
library(dplyr)
library(stats)
library(xts)
library(forecast)
library(stats)
library(lmtest)
```

```{r setwd, include=FALSE}
setwd("C:/Users/maxku/OneDrive/Documents/Silas/Silas_Project")
```

```{r readxlsx}
# read-in excel data
df <- readxl::read_excel("Data_Is_Key.xlsx")
```

```{r datawrangling, include=FALSE}
# rename and convert Data
df <- df %>% rename(Wochentag = `Datum (jjmmtt)`) %>% mutate(Wochentag = as.Date(Wochentag, format = "%y%m%d"))

df <- df %>% mutate_at(c("Flughafen", "Airline", "Zeit", "Device", "Datenzugriff"), as.factor) %>% 
  mutate_at(c("Cookies", "IP-Adresse"), as.logical)

df <- df %>% rename(Preis = `Preis (€)`) %>% rename(IP_Adresse = `IP-Adresse`)

levels(df$Flughafen) <- c('Amsterdam', 'Berlin', 'Lissabon', 'London', 'Bangkok', 'New York', 'Tokio')
levels(df$Airline) <- c('AUA', 'KLM', 'EZY', 'LDM', 'BAW', 'THA', 'UAL', 'ANA')

```

# Hypothese 1 - Einzelflüge
```{r data_H1, fig.width=15, fig.height=7}
# 1)
# Modell 1: Preis in Abhängigkeit von Zeit und Wochentag

# Dazu müssen wir zuerst Wochentag nach Mo, Di, Mi, ... kategorisieren

df1 <- df %>% mutate(Wochentag = weekdays(Wochentag)) %>% mutate(Wochentag = factor(Wochentag, levels = c("Montag",
                                                                                          "Dienstag",
                                                                                          "Mittwoch",
                                                                                          "Donnerstag",
                                                                                          "Freitag",
                                                                                          "Samstag",
                                                                                          "Sonntag"))) %>%
  filter(Device == 0 & Datenzugriff == 0 & Cookies == FALSE & IP_Adresse == FALSE) %>% 
  unite(Flughafen_Airline, c("Flughafen", "Airline"), sep = "-") %>% 
  select(Flughafen_Airline,Preis, Wochentag, Zeit) 
# rename levels für Zeit
levels(df1$Zeit) <- c("Morgen", "Mittag", "Abend")

#levels(df1$Wochentag)
#str(df)
```

## Deskriptive Statistik - Einzelflüge
````{r}
temp <- c()
for (flug in unique(df1$Flughafen_Airline)){
  df1_single <- df1 %>% dplyr::filter(Flughafen_Airline == flug)
  
  temp <- c(temp, jmv::descriptives(df1_single, vars = c("Preis", "Wochentag", "Zeit"), sd = TRUE, missing = TRUE, freq = TRUE))
}
names(temp) <- paste('Flug:', unique(df1$Flughafen_Airline))
temp
````


## Box-Plot - Einzelflüge
````{r, fig.width=15, fig.height=7}

for (flug in unique(df1$Flughafen_Airline)){
  df1_single <- df1 %>% dplyr::filter(Flughafen_Airline == flug)
  
  jmv::descriptives(df1_single, vars = c("Preis", "Wochentag", "Zeit"), sd = TRUE, missing = TRUE, freq = F)

  # Plot Box_Plot
  gp<-ggplot(df1_single, aes(Wochentag, Preis)) +
    geom_boxplot(aes(fill = Wochentag), show.legend = TRUE) +
    geom_point() +
    facet_wrap(~Zeit) +
    ggtitle(paste('Flug:', flug))
  
  print(gp)

}

````

## ANOVA
````{r, fig.width=15, fig.height=7}
temp <- c()
for (flug in unique(df1$Flughafen_Airline)){
  df1_single <- df1 %>% dplyr::filter(Flughafen_Airline == flug)
  
  # Mehrfakorielle ANOVA:
  
  Anova1<-jmv::ANOVA(data = df1_single, 
                     dep = "Preis",
                     factors = c("Wochentag", "Zeit"),
                     modelTerms = list("Wochentag", "Zeit"),
                     effectSize = "partEta",
                     emMeans = list(
                       c("Wochentag", "Zeit")
                     ),
                     emmTables = TRUE
  )
  temp <- c(temp, Anova1)
}
names(temp) <- paste('Flug:', unique(df1$Flughafen_Airline))
temp
````
